micronaut:
  application:
    name: Books Application

# For Flyway
datasources:
  default:
    url: ${DATASOURCE_URL:`jdbc:postgresql://localhost:5432/app_db`}
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:app_user}
    password: ${DATASOURCE_PASSWORD:app_password}

# For Application
r2dbc:
  datasources:
    default:
      url: ${R2DBC_URL:`r2dbc:postgresql://localhost:5432/app_db`}
      username: ${DATASOURCE_USERNAME:app_user}
      password: ${DATASOURCE_PASSWORD:app_password}

flyway:
  datasources:
    default:
      enabled: true