CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    isbn VARCHAR(32) NOT NULL,
    person_id BIGINT NOT NULL,
    CONSTRAINT fk_book_person FOREIGN KEY (person_id) REFERENCES person (id),
    CONSTRAINT uk_book_isbn UNIQUE (isbn)
);

INSERT INTO person (id, first_name, last_name) VALUES (1, 'Person1', 'Demo1');
INSERT INTO person (id, first_name, last_name) VALUES (2, 'Person2', 'Demo2');
INSERT INTO person (id, first_name, last_name) VALUES (3, 'Person3', 'Demo3');
INSERT INTO person (id, first_name, last_name) VALUES (4, 'Person4', 'Demo4');
INSERT INTO person (id, first_name, last_name) VALUES (5, 'Person5', 'Demo5');
INSERT INTO person (id, first_name, last_name) VALUES (6, 'Person6', 'Demo6');
INSERT INTO person (id, first_name, last_name) VALUES (7, 'Person7', 'Demo7');
INSERT INTO person (id, first_name, last_name) VALUES (8, 'Person8', 'Demo8');
INSERT INTO person (id, first_name, last_name) VALUES (9, 'Person9', 'Demo9');
INSERT INTO person (id, first_name, last_name) VALUES (10, 'Person10', 'Demo10');

INSERT INTO book (id, title, isbn, person_id) VALUES (1, 'Book 1-1', 'ISBN-001-01', 1);
INSERT INTO book (id, title, isbn, person_id) VALUES (2, 'Book 1-2', 'ISBN-001-02', 1);
INSERT INTO book (id, title, isbn, person_id) VALUES (3, 'Book 1-3', 'ISBN-001-03', 1);
INSERT INTO book (id, title, isbn, person_id) VALUES (4, 'Book 1-4', 'ISBN-001-04', 1);
INSERT INTO book (id, title, isbn, person_id) VALUES (5, 'Book 1-5', 'ISBN-001-05', 1);
INSERT INTO book (id, title, isbn, person_id) VALUES (6, 'Book 2-1', 'ISBN-002-01', 2);
INSERT INTO book (id, title, isbn, person_id) VALUES (7, 'Book 2-2', 'ISBN-002-02', 2);
INSERT INTO book (id, title, isbn, person_id) VALUES (8, 'Book 2-3', 'ISBN-002-03', 2);
INSERT INTO book (id, title, isbn, person_id) VALUES (9, 'Book 2-4', 'ISBN-002-04', 2);
INSERT INTO book (id, title, isbn, person_id) VALUES (10, 'Book 2-5', 'ISBN-002-05', 2);
INSERT INTO book (id, title, isbn, person_id) VALUES (11, 'Book 3-1', 'ISBN-003-01', 3);
INSERT INTO book (id, title, isbn, person_id) VALUES (12, 'Book 3-2', 'ISBN-003-02', 3);
INSERT INTO book (id, title, isbn, person_id) VALUES (13, 'Book 3-3', 'ISBN-003-03', 3);
INSERT INTO book (id, title, isbn, person_id) VALUES (14, 'Book 3-4', 'ISBN-003-04', 3);
INSERT INTO book (id, title, isbn, person_id) VALUES (15, 'Book 3-5', 'ISBN-003-05', 3);
INSERT INTO book (id, title, isbn, person_id) VALUES (16, 'Book 4-1', 'ISBN-004-01', 4);
INSERT INTO book (id, title, isbn, person_id) VALUES (17, 'Book 4-2', 'ISBN-004-02', 4);
INSERT INTO book (id, title, isbn, person_id) VALUES (18, 'Book 4-3', 'ISBN-004-03', 4);
INSERT INTO book (id, title, isbn, person_id) VALUES (19, 'Book 4-4', 'ISBN-004-04', 4);
INSERT INTO book (id, title, isbn, person_id) VALUES (20, 'Book 4-5', 'ISBN-004-05', 4);
INSERT INTO book (id, title, isbn, person_id) VALUES (21, 'Book 5-1', 'ISBN-005-01', 5);
INSERT INTO book (id, title, isbn, person_id) VALUES (22, 'Book 5-2', 'ISBN-005-02', 5);
INSERT INTO book (id, title, isbn, person_id) VALUES (23, 'Book 5-3', 'ISBN-005-03', 5);
INSERT INTO book (id, title, isbn, person_id) VALUES (24, 'Book 5-4', 'ISBN-005-04', 5);
INSERT INTO book (id, title, isbn, person_id) VALUES (25, 'Book 5-5', 'ISBN-005-05', 5);
INSERT INTO book (id, title, isbn, person_id) VALUES (26, 'Book 6-1', 'ISBN-006-01', 6);
INSERT INTO book (id, title, isbn, person_id) VALUES (27, 'Book 6-2', 'ISBN-006-02', 6);
INSERT INTO book (id, title, isbn, person_id) VALUES (28, 'Book 6-3', 'ISBN-006-03', 6);
INSERT INTO book (id, title, isbn, person_id) VALUES (29, 'Book 6-4', 'ISBN-006-04', 6);
INSERT INTO book (id, title, isbn, person_id) VALUES (30, 'Book 6-5', 'ISBN-006-05', 6);
INSERT INTO book (id, title, isbn, person_id) VALUES (31, 'Book 7-1', 'ISBN-007-01', 7);
INSERT INTO book (id, title, isbn, person_id) VALUES (32, 'Book 7-2', 'ISBN-007-02', 7);
INSERT INTO book (id, title, isbn, person_id) VALUES (33, 'Book 7-3', 'ISBN-007-03', 7);
INSERT INTO book (id, title, isbn, person_id) VALUES (34, 'Book 7-4', 'ISBN-007-04', 7);
INSERT INTO book (id, title, isbn, person_id) VALUES (35, 'Book 7-5', 'ISBN-007-05', 7);
INSERT INTO book (id, title, isbn, person_id) VALUES (36, 'Book 8-1', 'ISBN-008-01', 8);
INSERT INTO book (id, title, isbn, person_id) VALUES (37, 'Book 8-2', 'ISBN-008-02', 8);
INSERT INTO book (id, title, isbn, person_id) VALUES (38, 'Book 8-3', 'ISBN-008-03', 8);
INSERT INTO book (id, title, isbn, person_id) VALUES (39, 'Book 8-4', 'ISBN-008-04', 8);
INSERT INTO book (id, title, isbn, person_id) VALUES (40, 'Book 8-5', 'ISBN-008-05', 8);
INSERT INTO book (id, title, isbn, person_id) VALUES (41, 'Book 9-1', 'ISBN-009-01', 9);
INSERT INTO book (id, title, isbn, person_id) VALUES (42, 'Book 9-2', 'ISBN-009-02', 9);
INSERT INTO book (id, title, isbn, person_id) VALUES (43, 'Book 9-3', 'ISBN-009-03', 9);
INSERT INTO book (id, title, isbn, person_id) VALUES (44, 'Book 9-4', 'ISBN-009-04', 9);
INSERT INTO book (id, title, isbn, person_id) VALUES (45, 'Book 9-5', 'ISBN-009-05', 9);
INSERT INTO book (id, title, isbn, person_id) VALUES (46, 'Book 10-1', 'ISBN-010-01', 10);
INSERT INTO book (id, title, isbn, person_id) VALUES (47, 'Book 10-2', 'ISBN-010-02', 10);
INSERT INTO book (id, title, isbn, person_id) VALUES (48, 'Book 10-3', 'ISBN-010-03', 10);
INSERT INTO book (id, title, isbn, person_id) VALUES (49, 'Book 10-4', 'ISBN-010-04', 10);
INSERT INTO book (id, title, isbn, person_id) VALUES (50, 'Book 10-5', 'ISBN-010-05', 10);